names  = [
    'Anti-Mage','Axe','Bane','Bloodseeker','Crystal Maiden','Drow Ranger','Earthshaker',
    'Juggernaut','Mirana','Morphling','Shadow Fiend','Phantom Lancer','Puck','Pudge','Razor',
    'Sand King','Storm Spirit','Sven','Tiny','Vengeful Spirit','Windranger','Zeus','Kunkka',
    'Lina','Lion','Shadow Shaman','Slardar','Tidehunter','Witch Doctor','Lich','Riki','Enigma',
    'Tinker','Sniper','Necrophos','Warlock','Beastmaster','Queen of Pain','Venomancer',
    'Faceless Void','Wraith King','Death Prophet','Phantom Assassin','Pugna',
    'Templar Assassin','Viper','Luna','Dragon Knight','Dazzle','Clockwerk','Leshrac',
    "Nature's Prophet",'Lifestealer','Dark Seer','Clinkz','Omniknight','Enchantress',
    'Huskar','Night Stalker','Broodmother','Bounty Hunter','Weaver','Jakiro','Batrider',
    'Chen','Spectre','Ancient Apparition','Doom','Ursa','Spirit Breaker','Gyrocopter',
    'Alchemist','Invoker','Silencer','Outworld Destroyer','Lycan','Brewmaster',
    'Shadow Demon','Lone Druid','Chaos Knight','Meepo','Treant Protector','Ogre Magi',
    'Undying','Rubick','Disruptor','Nyx Assassin','Naga Siren','Keeper of the Light','Io',
    'Visage','Slark','Medusa','Troll Warlord','Centaur Warrunner','Magnus','Timbersaw',
    'Bristleback','Tusk','Skywrath Mage','Abaddon','Elder Titan','Legion Commander',
    'Techies','Ember Spirit','Earth Spirit','Underlord','Terrorblade','Phoenix','Oracle',
    'Winter Wyvern','Arc Warden','Monkey King','Dark Willow','Pangolier','Grimstroke',
    'Hoodwink','Void Spirit','Snapfire','Mars','Dawnbreaker'
]

ids = [
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,25,
    26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,
    47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,
    68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,
    89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,
    108,109,110,111,112,113,114,119,120,121,123,126,128,129,135
]

roles = [
 ['Carry', 'Escape', 'Nuker'],
 ['Initiator', 'Durable', 'Disabler', 'Jungler', 'Carry'],
 ['Support', 'Disabler', 'Nuker', 'Durable'],
 ['Carry', 'Disabler', 'Jungler', 'Nuker', 'Initiator'],
 ['Support', 'Disabler', 'Nuker', 'Jungler'],
 ['Carry', 'Disabler', 'Pusher'],
 ['Support', 'Initiator', 'Disabler', 'Nuker'],
 ['Carry', 'Pusher', 'Escape'],
 ['Carry', 'Support', 'Escape', 'Nuker', 'Disabler'],
 ['Carry', 'Escape', 'Durable', 'Nuker', 'Disabler'],
 ['Carry', 'Nuker'],
 ['Carry', 'Escape', 'Pusher', 'Nuker'],
 ['Initiator', 'Disabler', 'Escape', 'Nuker'],
 ['Disabler', 'Initiator', 'Durable', 'Nuker'],
 ['Carry', 'Durable', 'Nuker', 'Pusher'],
 ['Initiator', 'Disabler', 'Support', 'Nuker', 'Escape', 'Jungler'],
 ['Carry', 'Escape', 'Nuker', 'Initiator', 'Disabler'],
 ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
 ['Carry', 'Nuker', 'Pusher', 'Initiator', 'Durable', 'Disabler'],
 ['Support', 'Initiator', 'Disabler', 'Nuker', 'Escape'],
 ['Carry', 'Support', 'Disabler', 'Escape', 'Nuker'],
 ['Nuker', 'Carry'],
 ['Carry', 'Support', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
 ['Support', 'Carry', 'Nuker', 'Disabler'],
 ['Support', 'Disabler', 'Nuker', 'Initiator'],
 ['Support', 'Pusher', 'Disabler', 'Nuker', 'Initiator'],
 ['Carry', 'Durable', 'Initiator', 'Disabler', 'Escape'],
 ['Initiator', 'Durable', 'Disabler', 'Nuker', 'Carry'],
 ['Support', 'Nuker', 'Disabler'],
 ['Support', 'Nuker'],
 ['Carry', 'Escape', 'Disabler'],
 ['Disabler', 'Jungler', 'Initiator', 'Pusher'],
 ['Carry', 'Nuker', 'Pusher'],
 ['Carry', 'Nuker'],
 ['Carry', 'Nuker', 'Durable', 'Disabler'],
 ['Support', 'Initiator', 'Disabler'],
 ['Initiator', 'Disabler', 'Durable', 'Nuker'],
 ['Carry', 'Nuker', 'Escape'],
 ['Support', 'Nuker', 'Initiator', 'Pusher', 'Disabler'],
 ['Carry', 'Initiator', 'Disabler', 'Escape', 'Durable'],
 ['Carry', 'Support', 'Durable', 'Disabler', 'Initiator'],
 ['Carry', 'Pusher', 'Nuker', 'Disabler'],
 ['Carry', 'Escape'],
 ['Nuker', 'Pusher'],
 ['Carry', 'Escape'],
 ['Carry', 'Durable', 'Initiator', 'Disabler'],
 ['Carry', 'Nuker', 'Pusher'],
 ['Carry', 'Pusher', 'Durable', 'Disabler', 'Initiator', 'Nuker'],
 ['Support', 'Nuker', 'Disabler'],
 ['Initiator', 'Disabler', 'Durable', 'Nuker'],
 ['Carry', 'Support', 'Nuker', 'Pusher', 'Disabler'],
 ['Carry', 'Jungler', 'Pusher', 'Escape', 'Nuker'],
 ['Carry', 'Durable', 'Jungler', 'Escape', 'Disabler'],
 ['Initiator', 'Jungler', 'Escape', 'Disabler'],
 ['Carry', 'Escape', 'Pusher'],
 ['Support', 'Durable', 'Nuker'],
 ['Support', 'Jungler', 'Pusher', 'Durable', 'Disabler'],
 ['Carry', 'Durable', 'Initiator'],
 ['Carry', 'Initiator', 'Durable', 'Disabler', 'Nuker'],
 ['Carry', 'Pusher', 'Escape', 'Nuker'],
 ['Escape', 'Nuker'],
 ['Carry', 'Escape'],
 ['Support', 'Nuker', 'Pusher', 'Disabler'],
 ['Initiator', 'Jungler', 'Disabler', 'Escape'],
 ['Support', 'Jungler', 'Pusher'],
 ['Carry', 'Durable', 'Escape'],
 ['Support', 'Disabler', 'Nuker'],
 ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
 ['Carry', 'Jungler', 'Durable', 'Disabler'],
 ['Carry', 'Initiator', 'Disabler', 'Durable', 'Escape'],
 ['Carry', 'Nuker', 'Disabler'],
 ['Carry', 'Support', 'Durable', 'Disabler', 'Initiator', 'Nuker'],
 ['Carry', 'Nuker', 'Disabler', 'Escape', 'Pusher'],
 ['Carry', 'Support', 'Disabler', 'Initiator', 'Nuker'],
 ['Carry', 'Nuker', 'Disabler'],
 ['Carry', 'Pusher', 'Jungler', 'Durable', 'Escape'],
 ['Carry', 'Initiator', 'Durable', 'Disabler', 'Nuker'],
 ['Support', 'Disabler', 'Initiator', 'Nuker'],
 ['Carry', 'Pusher', 'Jungler', 'Durable'],
 ['Carry', 'Disabler', 'Durable', 'Pusher', 'Initiator'],
 ['Carry', 'Escape', 'Nuker', 'Disabler', 'Initiator', 'Pusher'],
 ['Support', 'Initiator', 'Durable', 'Disabler', 'Escape'],
 ['Support', 'Nuker', 'Disabler', 'Durable', 'Initiator'],
 ['Support', 'Durable', 'Disabler', 'Nuker'],
 ['Support', 'Disabler', 'Nuker'],
 ['Support', 'Disabler', 'Nuker', 'Initiator'],
 ['Disabler', 'Nuker', 'Initiator', 'Escape'],
 ['Carry', 'Support', 'Pusher', 'Disabler', 'Initiator', 'Escape'],
 ['Support', 'Nuker', 'Disabler', 'Jungler'],
 ['Support', 'Escape', 'Nuker'],
 ['Support', 'Nuker', 'Durable', 'Disabler', 'Pusher'],
 ['Carry', 'Escape', 'Disabler', 'Nuker'],
 ['Carry', 'Disabler', 'Durable'],
 ['Carry', 'Pusher', 'Disabler', 'Durable'],
 ['Durable', 'Initiator', 'Disabler', 'Nuker', 'Escape'],
 ['Initiator', 'Disabler', 'Nuker', 'Escape'],
 ['Nuker', 'Durable', 'Escape'],
 ['Carry', 'Durable', 'Initiator', 'Nuker'],
 ['Initiator', 'Disabler', 'Nuker'],
 ['Support', 'Nuker', 'Disabler'],
 ['Support', 'Carry', 'Durable'],
 ['Initiator', 'Disabler', 'Nuker', 'Durable'],
 ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
 ['Nuker', 'Disabler'],
 ['Carry', 'Escape', 'Nuker', 'Disabler', 'Initiator'],
 ['Nuker', 'Escape', 'Disabler', 'Initiator', 'Durable'],
 ['Support', 'Nuker', 'Disabler', 'Durable', 'Escape'],
 ['Carry', 'Pusher', 'Nuker'],
 ['Support', 'Nuker', 'Initiator', 'Escape', 'Disabler'],
 ['Support', 'Nuker', 'Disabler', 'Escape'],
 ['Support', 'Disabler', 'Nuker'],
 ['Carry', 'Escape', 'Nuker'],
 ['Carry', 'Escape', 'Disabler', 'Initiator'],
 ['Support', 'Nuker', 'Disabler', 'Escape'],
 ['Carry', 'Nuker', 'Disabler', 'Durable', 'Escape', 'Initiator'],
 ['Support', 'Nuker', 'Disabler', 'Escape'],
 ['Nuker', 'Escape', 'Disabler'],
 ['Carry', 'Escape', 'Nuker', 'Disabler'],
 ['Support', 'Nuker', 'Disabler', 'Escape'],
 ['Carry', 'Initiator', 'Disabler', 'Durable'],
 ['Carry', 'Durable']
]
